apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets
  namespace: external-secrets
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/external-secrets/external-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-secrets
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: external-secrets
    namespace: external-secrets
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets-store
  namespace: external-secrets
spec:
  dependsOn:
  - name: cluster-apps-external-secrets
  interval: 5m
  path: "./kubernetes/apps/external-secrets/external-secrets/stores"
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-secrets
