namePrefix: net-

resources:
- traefik/helmrelease.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# patches:
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: traefik
#   patch: |-
#     - op: remove
#       path: /spec/template/spec/securityContext
