
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: dev-secret-store
spec:
  provider:
    gcpsm:
      projectID: ninjawombat #GCP projectID
      auth:
        workloadIdentity:
          clusterLocation: us-west4-b #GKE cluster location
          clusterName: ninjawombat #GKE clustername
          serviceAccountRef:
            name: external-secrets #KSA_NAME

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-password-1
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: dev-secret-store # name of the SecretStore (or kind specified)
  target:
    name: demo-password-1 # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: demo-password-1 # name of the GCPSM secret key
    remoteRef:
      key: demo-password-1
