projects:
- name: networking
  namespace: argocd
  additionalLabels: {}
  additionalAnnotations: {}
  permitOnlyProjectScopedClusters: false
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  description: Networking Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: networking
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceNamespaces:
  - networking

applications:
- name: networking
  namespace: argocd
  project: networking
  source:
    repoURL: https://github.com/rastydnb/home-cheap-gke-cluster.git
    targetRevision: HEAD
    path: argocd/manifests/networking
    directory:
      recurse: false
  destination:
    namespace: networking
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true






# project: networking
# source:
#   repoURL: 'https://traefik.github.io/charts'
#   targetRevision: 24.0.0
#   chart: traefik
# destination:
#   server: 'https://kubernetes.default.svc'
#   namespace: networking
# syncPolicy:
#   automated:
#     prune: true
#     selfHeal: true
#   syncOptions:
#     - CreateNamespace=true
